// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// simulated_B
arma::mat simulated_B(List attributes, List parm, arma::cube data);
RcppExport SEXP _BCFM_simulated_B(SEXP attributesSEXP, SEXP parmSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_B(attributes, parm, data));
    return rcpp_result_gen;
END_RCPP
}
// simulated_X
arma::cube simulated_X(List attributes, List parm, arma::cube data);
RcppExport SEXP _BCFM_simulated_X(SEXP attributesSEXP, SEXP parmSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_X(attributes, parm, data));
    return rcpp_result_gen;
END_RCPP
}
// simulated_Z
arma::mat simulated_Z(List attributes, List parm);
RcppExport SEXP _BCFM_simulated_Z(SEXP attributesSEXP, SEXP parmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_Z(attributes, parm));
    return rcpp_result_gen;
END_RCPP
}
// simulated_mu
arma::mat simulated_mu(List attributes, List hyp_parm, List parm);
RcppExport SEXP _BCFM_simulated_mu(SEXP attributesSEXP, SEXP hyp_parmSEXP, SEXP parmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type hyp_parm(hyp_parmSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_mu(attributes, hyp_parm, parm));
    return rcpp_result_gen;
END_RCPP
}
// simulated_omega
arma::cube simulated_omega(List attributes, List hyp_parm, List parm);
RcppExport SEXP _BCFM_simulated_omega(SEXP attributesSEXP, SEXP hyp_parmSEXP, SEXP parmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type hyp_parm(hyp_parmSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_omega(attributes, hyp_parm, parm));
    return rcpp_result_gen;
END_RCPP
}
// simulated_probs
arma::vec simulated_probs(List attributes, List parm, List hyp_parm);
RcppExport SEXP _BCFM_simulated_probs(SEXP attributesSEXP, SEXP parmSEXP, SEXP hyp_parmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    Rcpp::traits::input_parameter< List >::type hyp_parm(hyp_parmSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_probs(attributes, parm, hyp_parm));
    return rcpp_result_gen;
END_RCPP
}
// simulated_sigma
arma::vec simulated_sigma(List attributes, List hyp_parm, List parm, arma::cube data);
RcppExport SEXP _BCFM_simulated_sigma(SEXP attributesSEXP, SEXP hyp_parmSEXP, SEXP parmSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type hyp_parm(hyp_parmSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    Rcpp::traits::input_parameter< arma::cube >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_sigma(attributes, hyp_parm, parm, data));
    return rcpp_result_gen;
END_RCPP
}
// simulated_tau
NumericVector simulated_tau(List attributes, List hypparm, List parm);
RcppExport SEXP _BCFM_simulated_tau(SEXP attributesSEXP, SEXP hypparmSEXP, SEXP parmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type attributes(attributesSEXP);
    Rcpp::traits::input_parameter< List >::type hypparm(hypparmSEXP);
    Rcpp::traits::input_parameter< List >::type parm(parmSEXP);
    rcpp_result_gen = Rcpp::wrap(simulated_tau(attributes, hypparm, parm));
    return rcpp_result_gen;
END_RCPP
}
// wdbryinverse
arma::mat wdbryinverse(arma::vec sigma2, arma::mat B, arma::mat Omega);
RcppExport SEXP _BCFM_wdbryinverse(SEXP sigma2SEXP, SEXP BSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sigma2(sigma2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(wdbryinverse(sigma2, B, Omega));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BCFM_simulated_B", (DL_FUNC) &_BCFM_simulated_B, 3},
    {"_BCFM_simulated_X", (DL_FUNC) &_BCFM_simulated_X, 3},
    {"_BCFM_simulated_Z", (DL_FUNC) &_BCFM_simulated_Z, 2},
    {"_BCFM_simulated_mu", (DL_FUNC) &_BCFM_simulated_mu, 3},
    {"_BCFM_simulated_omega", (DL_FUNC) &_BCFM_simulated_omega, 3},
    {"_BCFM_simulated_probs", (DL_FUNC) &_BCFM_simulated_probs, 3},
    {"_BCFM_simulated_sigma", (DL_FUNC) &_BCFM_simulated_sigma, 4},
    {"_BCFM_simulated_tau", (DL_FUNC) &_BCFM_simulated_tau, 3},
    {"_BCFM_wdbryinverse", (DL_FUNC) &_BCFM_wdbryinverse, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BCFM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
