#' @title Fit BCFM Model
#' @description Fits a single Bayesian Clustering Factor Model (BCFM) using C++
#' implementation. This function serves as a wrapper for the BCFMcpp function,
#' handling timing and output formatting.
#'
#' @param data An array of dimensions (observations, variables, time points)
#' @param model.attributes Model attributes generated by initialize.model.attributes
#' @param hyp.parm Hyperparameters generated by initialize.hyp.parm
#' @param n.iter Number of MCMC iterations. Default is 50000.
#' @param vague.mu Logical indicating whether to use vague priors for mu.
#'   Default is FALSE.
#' @param covariance Logical indicating whether to model covariance structure.
#'   Default is TRUE.
#' @param p.exponent The Dirichlet priors exponent for probabilities. Default is 2.
#' @param every Integer specifying the frequency of progress updates during MCMC.
#'   Default is 10.
#'
#' @return A list containing:
#' \describe{
#'   \item{Result}{Output from the BCFMcpp C++ function}
#'   \item{model.attributes}{The model attributes used}
#'   \item{hyp.parm}{The hyperparameters used}
#'   \item{start.time}{POSIXct timestamp when model started}
#'   \item{end.time}{POSIXct timestamp when model completed}
#'   \item{run.time}{Total elapsed time for model execution}
#' }
#'
#' @examples
#' \dontrun{
#' # Prepare data
#' data.pre <- init.data(mydata, c("var1", "var2", "var3"))
#'
#' # Initialize model components
#' model.attributes <- initialize.model.attributes(S = 100, times = 1,
#'                                                  R = 3, L = 2, G = 3)
#' cluster.hyperparms <- initialize.cluster.hyperparms(data.pre, model.attributes)
#' hyp.parm <- initialize.hyp.parm(model.attributes, cluster.hyperparms)
#'
#' # Fit model
#' result <- BCFM.fit(data.pre, model.attributes, hyp.parm,
#'                    n.iter = 10000, every = 100)
#' print(result$run.time)
#' }
#'
#' @seealso \code{\link{BCFM.model.selection}} for fitting multiple models,
#'   \code{\link{initialize.model.attributes}}, \code{\link{initialize.hyp.parm}}
#'
#' @export
BCFM.fit <- function(data, model.attributes, hyp.parm, n.iter = 50000,
                     vague.mu = FALSE, covariance = TRUE, p.exponent = 2,
                     every = 10) {
  tic <- Sys.time()
  message("Running BCFM")

  SDresult <- BCFMcpp(data, model.attributes, hyp.parm, n.iter,
                      verbose = TRUE, every = every)

  toc <- Sys.time()
  run.time <- toc - tic

  output <- list(
    Result = SDresult,
    model.attributes = model.attributes,
    hyp.parm = hyp.parm,
    start.time = tic,
    end.time = toc,
    run.time = run.time
  )

  return(output)
}
