# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Simulate Bs
#' @param attributes Attributes of the model and the data
#' @param parm Current estimated parameters
#' @param data Dataset of a 3-dimensional array
#' @noRd
simulated_B <- function(attributes, parm, data) {
    .Call(`_BCFM_simulated_B`, attributes, parm, data)
}

#' @title Simulate Xs
#' @param attributes Attributes of the model and the data
#' @param parm Current estimated parameters
#' @param data A 3-dimensional array dataset
#' @noRd
simulated_X <- function(attributes, parm, data) {
    .Call(`_BCFM_simulated_X`, attributes, parm, data)
}

#' @title Simulate Zs
#' @param attributes Attributes of the model and the data
#' @param parm Current estimated parameters
#' @noRd
simulated_Z <- function(attributes, parm) {
    .Call(`_BCFM_simulated_Z`, attributes, parm)
}

#' @title Simulate mus
#' @param attributes Attributes of the model and the data
#' @param hyp_parm Hyperparameters
#' @param parm Current estimated parameters
#' @noRd
simulated_mu <- function(attributes, hyp_parm, parm) {
    .Call(`_BCFM_simulated_mu`, attributes, hyp_parm, parm)
}

#' @title Simulate Omegas
#' @param attributes Attributes of the model and the data
#' @param hyp_parm Hyperparameters
#' @param parm Current estimated parameters
#' @noRd
simulated_omega <- function(attributes, hyp_parm, parm) {
    .Call(`_BCFM_simulated_omega`, attributes, hyp_parm, parm)
}

#' @title Simulate probabilities
#' @param attributes Attributes of the model and the data
#' @param parm Current estimated parameters
#' @param hyp_parm Hyperparameters
#' @noRd
simulated_probs <- function(attributes, parm, hyp_parm) {
    .Call(`_BCFM_simulated_probs`, attributes, parm, hyp_parm)
}

#' @title Simulate sigma squared
#' @param attributes Attributes of the model and the data
#' @param hyp_parm Hyperparameters
#' @param parm Current estimated parameters
#' @param data A 3-dimensional array dataset
#' @noRd
simulated_sigma <- function(attributes, hyp_parm, parm, data) {
    .Call(`_BCFM_simulated_sigma`, attributes, hyp_parm, parm, data)
}

#' @title Simulate taus
#' @param attributes Attributes of the model and the data
#' @param hypparm Hyperparameters
#' @param parm Current estimated parameters
#' @noRd
simulated_tau <- function(attributes, hypparm, parm) {
    .Call(`_BCFM_simulated_tau`, attributes, hypparm, parm)
}

wdbryinverse <- function(sigma2, B, Omega) {
    .Call(`_BCFM_wdbryinverse`, sigma2, B, Omega)
}

